### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by tempus2016** [Andre0512/hon#11]
I receive this error every time I try to set up the integration. 

This error originated from a custom integration.

```
Logger: homeassistant.config_entries
Source: custom_components/hon/__init__.py:32 
Integration: Haier hOn (documentation, issues) 
First occurred: 07:45:15 (3 occurrences) 
Last logged: 07:48:18

Error setting up entry xxx@live.co.uk for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 32, in async_setup_entry
    await hon.setup()
  File "/usr/local/lib/python3.10/site-packages/pyhon/api.py", line 54, in setup
    headers=await self._headers) as resp:
  File "/usr/local/lib/python3.10/site-packages/pyhon/api.py", line 44, in _headers
    if await auth.authorize(self._email, self._password, self._mobile_id):
  File "/usr/local/lib/python3.10/site-packages/pyhon/auth.py", line 144, in authorize
    if not await self._get_token(session, url):
  File "/usr/local/lib/python3.10/site-packages/pyhon/auth.py", line 116, in _get_token
    async with session.get(url[0]) as resp:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 508, in _request
    req = self._request_class(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 364, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: /SmartHome/_ui/system/security/ChangePassword?retURL=/SmartHome/setup/secur/RemoteAccessAuthorizationPage.apexp?source%3DCAAAAYdF3NxSMDAwMDAwMDAwMDAwMDAwAAAA8sbnEX8dpUqQX_4LLtIz8sY-PYEWuUNbA3FBywvLwODN1VBKZeyocPhtGmQg8nqwh13R0gNRNkWwfjETjavXdS4jzomsiVBxk5FYTymhGCPJ5r58wi7S2zKL-QbEIZmnRk3YPjx9NgxKtNCEKwJxFsjPtmUA9o66MXCOjTaBtPsSxlCVpCy1hOhll8YzFztNyPIk-0P2ARHhnecbF8vbr87UWC6STm4T7HAf9vUSV7g6db4aF0tJ_Bz6eRiHrF-SLKTbImHonDzZ_I8i0kLBgRPiwnJ4kspqMUqbMNVwtC_mvQpAcW0UHNtYfMnxo2LLKbl6H33cy2NZaahBO4_KxYBtlnkeL186bwBtRw5oNZT_OH5LwLI9B38TvA95u5UD10-aABP0nCE5lv8P2IIGtAhiyhXq4J5nk5MkE6bDVrPxezun71eWniUaR-VyxwSr7NXGNC2ealm7sV3eyGyQP8WdQOLI5bjkGWUe8UJAbTrmo5yXPfSJIgsU-DkzB-4yetUbrrBbTRIKjOnb9CXlhSn7XhvapaO2XTx15rVymeQw_S7MdKce51nqDSVxaZqgApn-u-04M76j6D67VJAyk5QS6K-6n_8zdSV38vLgWvA72M4WA5x-oBCSfAfzGUG2MgBWx7JLZj5YCc6Or9hCROctmHuqaJ2PoyScLgkw-CGRElEisHglBmZbvzX7DoeBEfRPjLw2jGC0ntlcNJ6Oxf8&fromFrontdoor=1&setupid=ChangePassword
```

**Comment by cddevlin6** [comment]
I am facing a similar issue! The integration had initially worked then stopped and I get that message in the logs.

**Comment by Andre0512** [comment]
For some reason you are requested to change your password.
Can someone test if the message also appears after you change the password via the app?
At the moment I don't know why you are redirected to this page or how to reproduce it...

**Comment by tempus2016** [comment]
> Hey, for some reason you are requested to change your password 🤔
> Can someone test if the message also appears after you change the password via the app?
> At the moment I don't know why you are redirected to this page or how to reproduce it...

I just tried. Still issues. 

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hon/__init__.py:32 
Integration: Haier hOn (documentation, issues) 
First occurred: 11:08:11 (1 occurrences) 
Last logged: 11:08:11

Error setting up entry john_mackinnon@live.co.uk for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 32, in async_setup_entry
    await hon.setup()
  File "/usr/local/lib/python3.10/site-packages/pyhon/api.py", line 54, in setup
    headers=await self._headers) as resp:
  File "/usr/local/lib/python3.10/site-packages/pyhon/api.py", line 44, in _headers
    if await auth.authorize(self._email, self._password, self._mobile_id):
  File "/usr/local/lib/python3.10/site-packages/pyhon/auth.py", line 142, in authorize
    if not (url := await self._login(session, email, password, fw_uid, loaded, login_url)):
  File "/usr/local/lib/python3.10/site-packages/pyhon/auth.py", line 104, in _login
    return (await response.json())["events"][0]["attributes"]["values"]["url"]
KeyError: 'events'
```

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hon/__init__.py:32 
Integration: Haier hOn (documentation, issues) 
First occurred: 11:07:22 (3 occurrences) 
Last logged: 11:14:59

Error setting up entry j@live.co.uk for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 32, in async_setup_entry
    await hon.setup()
  File "/usr/local/lib/python3.10/site-packages/pyhon/api.py", line 54, in setup
    headers=await self._headers) as resp:
  File "/usr/local/lib/python3.10/site-packages/pyhon/api.py", line 44, in _headers
    if await auth.authorize(self._email, self._password, self._mobile_id):
  File "/usr/local/lib/python3.10/site-packages/pyhon/auth.py", line 144, in authorize
    if not await self._get_token(session, url):
  File "/usr/local/lib/python3.10/site-packages/pyhon/auth.py", line 116, in _get_token
    async with session.get(url[0]) as resp:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 508, in _request
    req = self._request_class(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 364, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: /SmartHome/setup/secur/RemoteAccessAuthorizationPage.apexp?source=CAAAAYdlfA8XMDAwMDAwMDAwMDAwMDAwAAAA8uApeUV7zmQH4QX2lPxnW-5eOgGjd1mJQpftDIe3RshfPzRWt1LWhbjjdW2ibc_A7BQknpQWywTXKdtvE_Btzckz0ksYGWfx8K0RhW8g29CiP4A_aSFABY7MrYrpglqR4DAq6Hn6wqdf-Xti0FjbGXRF_FJEvM8uNPTo1TOC2jMlS0ilxplUBPFl_MqSA8mHasXAGGC4G048IRHhTeF67oUwXtjlznpapJUl2FyrMbuvYLVthe4Jb60-LKHRYUPijW9RcUzA7ovq2PtBKYs32WzwCcVkfGvYXjoDanvXLzSaJg2B2mJQdREJ8ExdSZOX4xWY3ThN6SGAIDDilhIKcZYo4_PpFeV1o2mt2O9euPbZv42esApA9seZDhwI8S78eVtbvOLoswwXxlm29i-7XDbP5lOXSLtIYxbbGSOK_btUyqF20QY2NBjcfPm3VG2ka-iBsCg2x14y4X_7BKCwMT--EaqvXG4V4CXN93c6PhnaPAcuzdV9E7P47VgFI-oej_jL0BD1taIPy2orPm8Y6W4TlHkkviuq-sVbHJNASMYG4zEVAGBb42kSgfmSdYhlxzZV0aP9PCTD7vinThWOzGhJOSH0w7jwxq-hLI9VtMOvGLvQWVBKGs5guRqRWQXbiow6-T9Yk5COBkMCTHpkVGWjVjCzlhGC_FbtOQS219kaUMP_YGuIDuI8Azrf5Yv2pMFWVVew1mEHWPxcHDFm48M
```

**Comment by cddevlin6** [comment]
I can log in fine with the Gvigroux version but I only see 3 sensors. When I used your (Andre0512) integration initially, I could see all the sensors I would expect. It then stopped working after a couple of days. The official hOn app is now showing an issue for me too and not loading.

**Comment by Andre0512** [comment]
Hey @tempus2016, sorry I have no idea how this can happen. I have released a beta version `v0.5.0-beta.1` with improved logging. Can you test it and send me the errors?
The version is installable via HACS if you allow beta versions.

**Comment by Andre0512** [comment]
@cddevlin6 so this integration works a few days for you and then starts failing with the exact error like @tempus2016?

The gvigroux login isn't implemented clean. Everyone is using his session, this couldn't be a solution :smiley: 

I have also problems with the official hOn app at the moment, the new version seems to be broken. In the app store are tons of complaints and haier answers that they have a massive cloud platform outage :thinking:

**Comment by bokkoman** [comment]
My official hOn app is working again.
There is a way to communicate directly with the washing/drying machine. But i haven't had success with that yet.

**Comment by Andre0512** [comment]
For me too, seems like they have fixed their problems :slightly_smiling_face: 
A direct connection would be nice, but I didn't find any open ports on my washing machine and when spoofing the traffic I can't find any direct communication.

**Comment by bokkoman** [comment]
> For me too, seems like they have fixed their problems 🙂 A direct connection would be nice, but I didn't find any open ports on my washing machine and when spoofing the traffic I can't find any direct communication.

I was referring to this
https://github.com/ofalvai/home-assistant-candy

**Comment by Andre0512** [comment]
This is for a different app with a different protocol (simply-fi). It looks like some devices can be accessed with both protocols, but my machine and some other newer devices can only work with the hOn protocol, so I can't test that. Maybe it is the strategy of Haier to rely only on the hOn app in the future or the simply-fi protocol is only implemented for devices produced by candy, I don't know. 
If you have more information or question about that, we better create a thread in the discussion section, because this issue was about an other topic :sweat_smile:

**Comment by Andre0512** [comment]
Nice, this are helpful information! Please try if it works with `v0.5.0-beta.4`

**Comment by Andre0512** [comment]
Thank you! :+1: :tada:
