### ISSUE TITLE
Washing machine and Tumble Dryer switches unavailable as of this morning.

### ISSUE THREAD

**Issue by finalbillybong** [Andre0512/hon#113]
As title. 

Both machines are in Remote mode and controllable by the hOn app.

Not much appearing in the logs.

```
This error originated from a custom integration.

Logger: custom_components.haier_hon.hon
Source: custom_components/haier_hon/hon.py:64
Integration: haier_hon
First occurred: 07:13:14 (1 occurrences)
Last logged: 07:13:14

Unexpected error fetching 90-38-0c-1c-51-d4 data: 'shadow'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier_hon/hon.py", line 64, in _async_update_data
    await self._device.update()
  File "/usr/local/lib/python3.11/site-packages/pyhon/appliance.py", line 261, in update
    await self.load_attributes()
  File "/usr/local/lib/python3.11/site-packages/pyhon/appliance.py", line 243, in load_attributes
    for name, values in self._attributes.pop("shadow").get("parameters").items():
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'shadow'

```
```

Logger: pyhon.hon
Source: /usr/local/lib/python3.11/site-packages/pyhon/hon.py:85
First occurred: 05:30:42 (4 occurrences)
Last logged: 08:43:09

'all_in_one_59_steam'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyhon/hon.py", line 77, in _create_appliance
    await asyncio.gather(
  File "/usr/local/lib/python3.11/site-packages/pyhon/appliance.py", line 218, in load_commands
    await self._add_favourites()
  File "/usr/local/lib/python3.11/site-packages/pyhon/appliance.py", line 228, in _add_favourites
    base = copy(self._commands[command_name].categories[program_name])
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'all_in_one_59_steam'
```
```
This error originated from a custom integration.

Logger: pyhon.hon
Source: custom_components/haier_hon/__init__.py:31
Integration: haier_hon
First occurred: 08:51:18 (1 occurrences)
Last logged: 08:51:18

Device data - {'purchaseDate': '2023-03-22T00:00:00.000Z', 'fwVersion': '5.13.0', 'waterHard': '3', 'applianceTypeId': 1, 'firstEnrollment': True, 'attributes': {'acuVersion': '9.A.B', 'chipset': 'ESP32D0WDQ5', 'dictionaryId': '99', 'fwLabel': 'iotfw_wmwd', 'lang': 'it-IT', 'uiVersion': '7.C.0'}, 'defaultWarrantyYears': 1, 'applianceModelId': 14, 'series': 'h-wash500', 'firstEnrollmentTBC': True, 'code': '31010433', 'SK': 'app#90-38-0c-1c-51-d4', 'macAddress': '90-38-0c-1c-51-d4', 'eepromName': '43033676', 'applianceId': '90-38-0c-1c-51-d4#2023-04-06T17:20:44Z', 'id': 14, 'modelName': 'HW 68AMC/1-80', 'applianceTypeName': 'WM', 'connectivity': 'wifi|ble', 'serialNumber': '3101043322313118', 'enrollmentDate': '2023-04-06T17:20:44.751Z', 'brand': 'hoover', 'lastUpdate': '2023-04-06T17:20:57Z', 'eepromId': 4, 'applianceStatus': 1, 'coords': {'lng': 0.3323485, 'lat': 53.2319965}, 'PK': 'user#eu-west-1:c2989f9a-a7d2-465b-941a-1e023780727c', 'sections': {'chatbot': False, 'ecoDelayStart': True}, 'topics': {'publish': [], 'subscribe': ['$aws/events/presence/disconnected/90-38-0c-1c-51-d4', '$aws/events/presence/connected/90-38-0c-1c-51-d4', 'haier/things/90-38-0c-1c-51-d4/event/appliancestatus/update', 'haier/things/90-38-0c-1c-51-d4/event/discovery/update']}}
```

Perhaps a change on hOn's side?

**Comment by finalbillybong** [comment]
A reboot of my router sorted this.
