### ISSUE TITLE
Integration fails to set up on 2024.1

### ISSUE THREAD

**Issue by finalbillybong** [Andre0512/hon#140]
Logs below:

```
Logger: homeassistant.loader
Source: loader.py:842 
First occurred: 21:52:43 (2 occurrences) 
Last logged: 21:52:43

Unexpected exception importing platform custom_components.haier_hon.switch
Unexpected exception importing platform custom_components.haier_hon.binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/haier_hon/switch.py", line 25, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
    _init_fn(all_init_fields,
  File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument
```

```
Logger: homeassistant.setup
Source: setup.py:403 
First occurred: 21:52:43 (2 occurrences) 
Last logged: 21:52:43

Unable to prepare setup for platform 'hon.switch': Platform not found (Exception importing custom_components.haier_hon.switch).
Unable to prepare setup for platform 'hon.binary_sensor': Platform not found (Exception importing custom_components.haier_hon.binary_sensor).
```

**Comment by willhaggan** [comment]
Same issue on 2024.1.1

**Comment by Andre0512** [comment]
Hi, do you use the recent version? The error message makes no sense :thinking:

**Comment by Andre0512** [comment]
Please check out `v0.11.0-beta.1`, maybe you can profit from another fix

**Comment by finalbillybong** [comment]
> Please check out `v0.11.0-beta.1`, maybe you can profit from another fix

Thank you but I’m getting same error with this version I am afraid.

**Comment by finalbillybong** [comment]
Just tested 2024.1.4 and this error persists for me even with v0.11.0

**Comment by finalbillybong** [comment]
Thanks for getting back to me on this. I am sure you're busy with other things, so I appreciate it.

I have this line in my sensor.py:

`@dataclass
class HonConfigSensorEntityDescription(SensorEntityDescription):
    entity_category: EntityCategory = EntityCategory.CONFIG
    option_list: Dict[str, str] = None`

So that seems correct to me?

**Comment by finalbillybong** [comment]
I will delete the whole hon folder and manually install the latest update from here and then update HA and see what happens!

**Comment by Andre0512** [comment]
> I have this line in my sensor.py:
> 
> `@dataclass class HonConfigSensorEntityDescription(SensorEntityDescription): entity_category: EntityCategory = EntityCategory.CONFIG option_list: Dict[str, str] = None`
> 
> So that seems correct to me?

It must be `EntityCategory.DIAGNOSTIC`, so I think it's a problem with the update.


> I will delete the whole hon folder and manually install the latest update from here and then update HA and see what happens!

That will fix it I think :slightly_smiling_face:

**Comment by finalbillybong** [comment]
Yep that did it. Thank you, @Andre0512 - I do wonder what happened though to cause this tangle....
