### ISSUE TITLE
ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by djvariado** [Andre0512/hon#164]
при запуске HA не запускается интеграция
в логах следующая ошибка:

Setup failed for custom integration 'hon': Unable to import component: No module named 'imp'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/hon/__init__.py", line 2, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

**Comment by AlbCod** [comment]
hi, same problem

**Comment by Magicpulse** [comment]
Same error

**Comment by Andre0512** [comment]
This integration never used 'imp'. You probably use the old one from gvigroux, see gvigroux/hon#121

**Comment by robertomontinaro80** [comment]
same problem here. Please fix it.

**Comment by csPinKie** [comment]
@robertomontinaro80  use python 3.11 as a workaround

**Comment by emredemirhan** [comment]
how can we use python 3.11?

**Comment by csPinKie** [comment]
> how can we use python 3.11?

install python 3.11 from python.org and use it as your programming interpreter in your programming environment, idk what u use to code (i use pycharm)

**Comment by ruudleijnse** [comment]
the issue is the `import imp` in the __init__.py if you repleace it with `import importlib` it should work. Or switch to https://github.com/gvigroux/hon
