### ISSUE TITLE
Can not login with correct email and password

### ISSUE THREAD

**Issue by maxifly** [Andre0512/hon#215]
v0.13.0

I use EVO application on my phone.|
I setup addon to HA, enter correct email and password (I check tis information by logout/login on phone)
In HA log I see that hon can not login
In integration setting I see my email "Setup fail" and "No device or entityes".

**Environment (please complete the following information):**
 - Home Assistant Version: core-2024.5.4
 - hOn Integration Versionv  0.13.0
 - pyhOn Version ???
 
**Additional context**

**Home Assistant Logs**
Check `System` -> `Logs` if you can find any logs related to this integration and post it here.

**Device Log**
Post your device info here (if available)
2024-06-01 17:10:34.864 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry maxpant@mail.ru for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/__init__.py", line 41, in async_setup_entry
    hon = await Hon(**kwargs).create()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/hon.py", line 74, in create
    await self.setup()
  File "/usr/local/lib/python3.12/site-packages/pyhon/hon.py", line 105, in setup
    appliances = await self.api.load_appliances()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/api.py", line 84, in load_appliances
    async with self._hon.get(f"{const.API_URL}/commands/v1/appliance") as resp:
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/handler/base.py", line 64, in get
    async with self._intercept(*args, **kwargs) as response:
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/handler/hon.py", line 74, in _intercept
    kwargs["headers"] = await self._check_headers(kwargs.get("headers", {}))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/handler/hon.py", line 64, in _check_headers
    await self.auth.authenticate()
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/auth.py", line 258, in authenticate
    if not (url := await self._login()):
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/auth.py", line 195, in _login
    await self._error_logger(response)
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/auth.py", line 96, in _error_logger
    raise exceptions.HonAuthenticationError("Can't login")
pyhon.exceptions.HonAuthenticationError: Can't login

**Comment by maxifly** [comment]
{"actions":[{"id":"79;a","state":"SUCCESS","returnValue":"Your login attempt has failed. Make sure the username and password are correct.","error":[]}],"context":{"mode":"PROD","app":"siteforce:loginApp2","contextPath":"/s/sfsites","pathPrefix":"","fwuid":"ZDROWDdLOGtXcTZqSWZiU19ZaDJFdzk4bkk0bVJhZGJCWE9mUC1IZXZRbmcyNDguMTAuNS01LjAuMTA","mlr":1,"loaded":{"APPLICATION@markup://siteforce:loginApp2":"CMiYVlPW6pOgNvM9UnJGCw"},"globalValueProviders":[{"type":"$Global","values":{"eswConfigDeveloperName":{"writable":true,"defaultValue":""},"isVoiceOver":{"writable":true,"defaultValue":false},"setupAppContextId":{"writable":true,"defaultValue":""},"density":{"writable":true,"defaultValue":""},"srcdoc":{"writable":false,"defaultValue":false},"appContextId":{"writable":true,"defaultValue":""},"dynamicTypeSize":{"writable":true,"defaultValue":""}}}],"enableAccessChecks":true,"apce":1,"dns":"c","lairn":[],"laerc":[],"lav":"60","mna":{"lightning":"interop"},"lff":{"ENABLE_MIXED_SHADOW_MODE":false,"ENABLE_LEGACY_SCOPE_TOKENS":false,"DISABLE_LIGHT_DOM_UNSCOPED_CSS":false},"arse":1,"acaf":1,"services":["markup://lightning:configProvider","markup://force:salesforceScopedModuleResolver","markup://force:ldsEngineCreator","markup://instrumentation:locatorService"]},"perfSummary":{"version":"core","request":39,"actions":{"79;a":{"total":20,"db":6}},"actionsTotal":20,"overhead":0}}

**Comment by tomaszwozniak** [comment]
1. Reset password in you hon app
2. Remove integration entry in haier h0n integration
3. Add again

**Comment by Feirbran** [comment]
Hello there, I'm having the same issue and I also tried what @tomaszwozniak suggested but gives me the same error.
My Logs:
Dettagli registro (ERRORE)
Registratore: homeassistant.config_entries
Fonte: config_entries.py:594
Prima occorrenza: 12:39:22 (7 occorrenze)
Ultima registrazione: 12:46:00

Error setting up entry fxxxxxxxxxxxx@gmail.com for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/__init__.py", line 41, in async_setup_entry
    hon = await Hon(**kwargs).create()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/hon.py", line 74, in create
    await self.setup()
  File "/usr/local/lib/python3.12/site-packages/pyhon/hon.py", line 105, in setup
    appliances = await self.api.load_appliances()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/api.py", line 84, in load_appliances
    async with self._hon.get(f"{const.API_URL}/commands/v1/appliance") as resp:
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/handler/base.py", line 64, in get
    async with self._intercept(*args, **kwargs) as response:
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/handler/hon.py", line 74, in _intercept
    kwargs["headers"] = await self._check_headers(kwargs.get("headers", {}))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/handler/hon.py", line 64, in _check_headers
    await self.auth.authenticate()
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/auth.py", line 258, in authenticate
    if not (url := await self._login()):
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/auth.py", line 195, in _login
    await self._error_logger(response)
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/auth.py", line 96, in _error_logger
    raise exceptions.HonAuthenticationError("Can't login")
pyhon.exceptions.HonAuthenticationError: Can't login

**Comment by mateuszfl** [comment]
I have the same error, I changed my password and unfortunately it didn't help.

**Comment by ikreis** [comment]
> 1. Reset password in you hon app
> 2. Remove integration entry in haier h0n integration
> 3. Add again

This fixed it for me. Seems so easy in the end, but was reluctant to choose "delete".

**Comment by mateuszfl** [comment]
Yes, I had exactly the same problem today, but before deleting it (because I had similar concerns) I tried to persistently add the integration again, it ended with an empty window without any message. It wasn't until I looked at the server's response that I saw the actual error information (duplicate).

Also, remove and re-add according to the instructions.

**Comment by daemon76** [comment]
Log in to the website https://account2.hon-smarthome.com using your login and password and turn off Two-Factor Verification in your account settings. It worked for me.

**Comment by mschmiedel** [comment]
Hmmm, I don't get it, I tried what is suggested here:

1. Delete Integration
2. Reset pwd
3. Login as @daemon76  suggested and make sure 2FA is deactivated
4. Readd Integration

I am stuck with the "Can't login" message posted by @Feirbran.

Maybe one thought, we had our account configured with Google Social Login, I reset the pwd today for the first time in like a year to get the integration to work. Might there be a difference on accounts that support social login? Could other people who have posted and cannot fix this confirm if this is the case on their account too?

**Comment by daemon76** [comment]
I did not use a social account, but it is possible that a social account is
handled differently.

pt., 28 cze 2024 o 18:13 mschmiedel ***@***.***> napisał(a):

**Comment by mschmiedel** [comment]
@daemon76 , just tomato it clear, I do not use the social login for the integration (this cannot work!), just created a pwd which I can use on the app and on the account2.hon-smarthome.com by hand, but not on the integration. 

I just checked the pyhOn library:

Exception is raising here:
<img width="625" alt="image" src="https://github.com/Andre0512/hon/assets/8091121/921307c6-5949-459e-897f-21b0604d4809">

Last thing it prints is this:
homeassistant  |   1     200 - https://account2.hon-smarthome.com/setup/secur/RemoteAccessAuthorizationPage.apexp?source

along with the full response body of that page, which has a few js if conditions for some redirect, but if I understand the code correctly from the auth.py, it seems to be looking for some "url=" regex, which it cannot find...

What is very strange, if I do the login in a browser, I never see the "RemoteAccessAuthorizationPage" in the log... 

Maybe a feedback for @Andre0512: I activated debug in the HomaAssistant Integration, for the auth flow, it would be great if in that case every visited URL with response codes would be logged.

**Comment by mschmiedel** [comment]
One more comment here. I checked out the phyOn library and made a manual test from my pc. I can successfully login outside of HomeAssistant using the library. So I guess it might be some difference with the aiohttp HomeAssistant provides (maybe not in every case). I will see if I find a way to log stuff like the user-agent headers (in case they are set) and such...

**Comment by mschmiedel** [comment]
This is very strange, I just retested (without deleting and adding the integration) and it worked, maybe it was just a coincidence that something was wrong on server-side and I tested the lib manually after the fix. Now it works and I got the entities...

**Comment by Triskae** [comment]
Same problem here ... Can't login, tried to change the password, tried to delete and install the integration again, nothing works ... 😢

**Comment by lacko-hub** [comment]
Same login issue here. Credentials are good as they works in mobile app or via http page. PWD reset, integration re-download did not help :/

Logger: pyhon.connection.auth
Zdroj: custom_components/hon/__init__.py:40
Integrácia: Haier hOn (dokumentácia, problémy)
Prvýkrát sa vyskytol: 15:00:32 (1 výskytov)
Naposledy prihlásený: 15:00:32

hOn Authentication Error 1 200 - https://account2.hon-smarthome.com/hOnRedirect?startURL=/setup/secur/RemoteAccessAuthorizationPage.apexp?source%3DCAAAAZCcuyfbMDAwMDAwMDAwMDAwMDAwAAAA-jGEjDOFdYNJvnsyTEtqgLI4J77jGIWl1fKBkdNyKx87uyWqDWy838nEzWhk0dZd4MSKxX9wTgvoLSoTTmLIfX0WskqVNrtoSgL1WUAIMA2B-PPgKAvVUTexDCkrmCowPLsCcR63UCdwGv_zwoTEzV9v8puPKSaQaW3cymIFXTsX5KWgC_VrvMmMbTZ6sFiuxzjjC9YadCsDY-gPgHdQMzh1Uln91qi9bTLSPrl66Se3MYy1NC-T7XHTU6WRp1HQ9TFnjkNu2BIGnaKEXpZuf2UmKghmO50q2As4rH2UGP9-BFxQxwjjf4YpNoOexoIG12V8R6uugQnPI0AvRq8H0t_Et-x-wydJsA0c26nZL1PREo3mCiWvWxjmwuOvquWL2BZwWgP7F99v8JNw0fKyDhWe0GQiMK4n8GanEm_thJtf7h9cTzV0C0H9-idbHrGIoJGvVoLHzsUuI5EGqTez4W10nRfzQreaPRlO4-zNRaubCtbtzfdQ0lsWW1qmVfbUiQgXVE1kuqFQnelStYPIiX0cZov_1xpt5He6ZsOgwPGr0ddoeXnbDQuzTnSFogXzTT8AI7DDRAMAuLJjnwsOwuX9RuQ8j9TEacnkXU9J9SehBdPH24xQMdoVGv34Fh-jvrFWsF5hCJ8RvIdk9-FQQ3u0i8suWjC2L2k-FYlXqFDbuX7e5YU5gFoyev9VCcwVaU7K8Eva5c49pyUZwjPE5qm-zlQkUGICmwYvwBccWBHoFAlKx6YCXcoD3GsAWNakGw%253D%253D%26display%3Dtouch ERROR - 200 -

**Comment by dszymczuk** [comment]
I have some error since 1st of July.
I've reset password, uninstall and install again integration. Still `pyhon.exceptions.HonAuthenticationError: Can't login`.

On mobile app works fine.

**Comment by mschmiedel** [comment]
Could it be that freshly changed passwords are not synced and might need some time? In my case it startet working when I ignored it for like 24h... ;) I guess the login flow that was reverse engineered in the pyHOn library might not be always 100% identical to what happens in the app. At the end it is not an official integration. ;)

**Comment by Rafapadilla93** [comment]
I have the same problem. I changed the password and then I looged into https://account2.hon-smarthome.com/ as @daemon76 suggested. It didn't work.

Does somebody know how to solve it?

Thank you so much!

**Comment by iancedev** [comment]
Same login issue here. The only thing I did different I think is that I had first created my hon account with Google sign-in, but as I noticed I needed a password to login I've reset password.
Still, can't login.

**Comment by Rafapadilla93** [comment]
It seems that the solution is here #230 
@Andre0512 has made a pull request that fixes this bug.

**Comment by Triskae** [comment]
> It seems that the solution is here #230 @addshore has made a fork with corrections https://github.com/addshore/hon
> 
> (It doesn't work for me)

It doesn't work for me neither :/

**Comment by goktugolmez** [comment]
I have same issue is there any update for this. I tested every method.

**Comment by thunderbug1** [comment]
I encountered the same issue, any updates on this?
