### ISSUE TITLE
Been running fine with Ver 13, failed to connect, now can't set up

### ISSUE THREAD

**Issue by itnassol** [Andre0512/hon#233]
Had this running for weeks with no issues, then this morning it lost connection, did the usual, restarts etc, and of course did a complete reinstall.

All I get now is failed to set up and this in the logs, and help would be amazing, thank you.

Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 15:13:59 (2 occurrences)
Last logged: 15:17:14

Error setting up entry andrew.smith@itnas-sol.com for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/__init__.py", line 41, in async_setup_entry
    hon = await Hon(**kwargs).create()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/hon.py", line 74, in create
    await self.setup()
  File "/usr/local/lib/python3.12/site-packages/pyhon/hon.py", line 105, in setup
    appliances = await self.api.load_appliances()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/api.py", line 84, in load_appliances
    async with self._hon.get(f"{const.API_URL}/commands/v1/appliance") as resp:
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/handler/base.py", line 64, in get
    async with self._intercept(*args, **kwargs) as response:
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/handler/hon.py", line 74, in _intercept
    kwargs["headers"] = await self._check_headers(kwargs.get("headers", {}))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/handler/hon.py", line 64, in _check_headers
    await self.auth.authenticate()
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/auth.py", line 256, in authenticate
    if not await self._load_login():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/auth.py", line 104, in _load_login
    login_url = await self._introduce()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/auth.py", line 128, in _introduce
    await self._error_logger(response)
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/auth.py", line 96, in _error_logger
    raise exceptions.HonAuthenticationError("Can't login")
pyhon.exceptions.HonAuthenticationError: Can't login

**Comment by skif443** [comment]
Same thing

**Comment by terierul** [comment]
duplicates https://github.com/Andre0512/hon/issues/230

**Comment by eti16** [comment]
Nach Update auf core_2024.7.1 selber fehler.

**Comment by sajikur** [comment]
same here. This error has been present in the logs for a few days: 
hOn Authentication Error 1 200 - https://account2.hon-smarthome.com/hOnRedirect?startURL=/setup/secur/RemoteAccessAuthorizationPage.apexp?source%3DCAAAAZC7Y5VaMDAwM... (ETC)

**Comment by ingcicala** [comment]
Same here ha 2024.7.2

**Comment by millenniumy2k** [comment]
Same here

**Comment by Maicolsara** [comment]
solution?

**Comment by terierul** [comment]
guys, I do repeat: is duplicate https://github.com/Andre0512/hon/issues/230
