### ISSUE TITLE
Interference with ZHA

### ISSUE THREAD

**Issue by ilbeppe83** [Andre0512/hon#240]
Hello,

I had to disable this integration because when it's active ZHA fails the initialization.
When the itegration is disabled everything works normally.

This issue occurs already from the version 0.13, I waited for the new version but the issue is still present.

Has anyone experiences the same issue?

Thank you!
Giuseppe

**Comment by fishscrounger** [comment]
I run both addons and they work fine. Anything in the logs that could shed more light on this?

**Comment by ilbeppe83** [comment]
Hello,

this is what I can find in the logs during home assistant reboot:

2024-09-04 14:34:24.118 WARNING (MainThread) [bellows.zigbee.application] Watchdog heartbeat timeout: EzspError('EZSP is not running')
2024-09-04 14:34:34.120 WARNING (MainThread) [bellows.zigbee.application] Watchdog heartbeat timeout: EzspError('EZSP is not running')
2024-09-04 14:34:44.121 WARNING (MainThread) [bellows.zigbee.application] Watchdog heartbeat timeout: EzspError('EZSP is not running')
2024-09-04 14:34:51.419 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('zha', 'd0e2336a80bb3deffc5d7940acb00e0f'): 37944.033985201}
2024-09-04 14:34:54.122 WARNING (MainThread) [bellows.zigbee.application] Watchdog heartbeat timeout: EzspError('EZSP is not running')
2024-09-04 14:34:54.122 WARNING (MainThread) [zigpy.application] Watchdog failure
2024-09-04T12:34:54.127604964Z Traceback (most recent call last):
2024-09-04T12:34:54.127615678Z   File "/usr/local/lib/python3.12/site-packages/zigpy/application.py", line 673, in _watchdog_loop
2024-09-04T12:34:54.127631671Z     await self.watchdog_feed()
2024-09-04T12:34:54.127646478Z   File "/usr/local/lib/python3.12/site-packages/zigpy/application.py", line 655, in watchdog_feed
2024-09-04T12:34:54.127657122Z     await self._watchdog_feed()
2024-09-04T12:34:54.127689141Z   File "/usr/local/lib/python3.12/site-packages/bellows/zigbee/application.py", line 1000, in _watchdog_feed
2024-09-04T12:34:54.127699848Z     (res,) = await self._ezsp.readCounters()
2024-09-04T12:34:54.127711461Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-04T12:34:54.127727357Z   File "/usr/local/lib/python3.12/site-packages/bellows/ezsp/__init__.py", line 212, in _command
2024-09-04T12:34:54.127738405Z     raise EzspError("EZSP is not running")
2024-09-04T12:34:54.127747508Z bellows.exception.EzspError: EZSP is not running_

This occurs only when HON integration is enabled, if I disable it I have no problems with ZHA.
Another detail: it seems that if I enable HON after the boot is complete ZHA works correctly until the next reboot.
