### ISSUE TITLE
Detected blocking call to import_module with args

### ISSUE THREAD

**Issue by mistermax80** [Andre0512/hon#246]
**Describe the bug**
I see this in log this error

`set 20 23:48:25 hpmini hass[21329]: 2024-09-20 23:48:25.403 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('pyhon.appliances.wm',) inside the event loop by custom integration 'hon' at custom_components/hon/__init__.py, line 34: hon = await Hon( (offender: /srv/homeassistant/lib/python3.12/site-packages/pyhon/appliance.py, line 52: self._extra: Optional[ApplianceBase] = importlib.import_module(), please create a bug report at https://github.com/Andre0512/hon/issues
set 20 23:48:25 hpmini hass[21329]: For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
set 20 23:48:25 hpmini hass[21329]: Traceback (most recent call last):
set 20 23:48:25 hpmini hass[21329]:   File "/srv/homeassistant/bin/hass", line 8, in <module>
set 20 23:48:25 hpmini hass[21329]:     sys.exit(main())
set 20 23:48:25 hpmini hass[21329]:   File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/__main__.py", line 209, in main
set 20 23:48:25 hpmini hass[21329]:     exit_code = runner.run(runtime_conf)
set 20 23:48:25 hpmini hass[21329]:   File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/runner.py", line 189, in run
set 20 23:48:25 hpmini hass[21329]:     return loop.run_until_complete(setup_and_run_hass(runtime_config))
set 20 23:48:25 hpmini hass[21329]:   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
set 20 23:48:25 hpmini hass[21329]:     self.run_forever()
set 20 23:48:25 hpmini hass[21329]:   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
set 20 23:48:25 hpmini hass[21329]:     self._run_once()
set 20 23:48:25 hpmini hass[21329]:   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1985, in _run_once
set 20 23:48:25 hpmini hass[21329]:     handle._run()
set 20 23:48:25 hpmini hass[21329]:   File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
set 20 23:48:25 hpmini hass[21329]:     self._context.run(self._callback, *self._args)
set 20 23:48:25 hpmini hass[21329]:   File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 752, in async_setup_locked
set 20 23:48:25 hpmini hass[21329]:     await self.async_setup(hass, integration=integration)
set 20 23:48:25 hpmini hass[21329]:   File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 604, in async_setup
set 20 23:48:25 hpmini hass[21329]:     result = await component.async_setup_entry(hass, self)
set 20 23:48:25 hpmini hass[21329]:   File "/home/homeassistant/.homeassistant/custom_components/hon/__init__.py", line 34, in async_setup_entry
set 20 23:48:25 hpmini hass[21329]:     hon = await Hon(`

**Comment by mastier** [comment]
```
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/awscrt/mqtt5.py", line 1471, in _on_publish
homeassistant  | 2024-11-01 15:48:32.753 WARNING (Dummy-2) [homeassistant.helpers.frame] Detected that custom integration 'haier_hon' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/haier_hon/sensor.py, line 849: self.async_write_ha_state(), please report it to the author of the 'haier_hon' custom integration
homeassistant  |     self._on_publish_cb(PublishReceivedData(publish_packet=publish_packet))
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/pyhon/connection/mqtt.py", line 105, in _on_publish_received
homeassistant  |     self._hon.notify()
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/pyhon/hon.py", line 130, in notify
homeassistant  |     self._notify_function(None)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 489, in async_set_updated_data
homeassistant  |     self.async_update_listeners()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
homeassistant  |     update_callback()
homeassistant  |   File "/config/custom_components/haier_hon/sensor.py", line 849, in _handle_coordinator_update
homeassistant  |     self.async_write_ha_state()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in async_write_ha_state
homeassistant  |     report_non_thread_safe_operation("async_write_ha_state")
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 229, in report_non_thread_safe_operation
homeassistant  |     report(
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 163, in report
homeassistant  |     _report_integration(what, integration_frame, level, error_if_integration)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 201, in _report_integration
homeassistant  |     raise RuntimeError(
homeassistant  | RuntimeError: Detected that custom integration 'haier_hon' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/haier_hon/sensor.py, line 849: self.async_write_ha_state(). Please report it to the author of the 'haier_hon' custom integration.
```
