### ISSUE TITLE
Error occurred loading flow for integration hon

### ISSUE THREAD

**Issue by bvdf0251** [Andre0512/hon#260]
**Describe the bug**

**To Reproduce**
1. Go to 'Devices and Services'
2. Click on 'add integration'
3. Scroll down to 'Haier Hon'

**Expected behavior**
I expect to see the Integration load to be able to configure it.

**Screenshots**

**Environment (please complete the following information):**
 - Home Assistant Version: [e.g. `2024.10.4`]
 - hOn Integration Version [e.g. `0.14.0`, can be found in HACS or device log]
 - pyhOn Version [e.g. `0.17.5`, can be found in device log]

**Additional context**
new to this integration, searched for same error in issue log, couldn't find it.

**Home Assistant Logs**
Check `System` -> `Logs` if you can find any logs related to this integration and post it here.

Logger: homeassistant.config_entries
Bron: config_entries.py:2945
Eerst voorgekomen: 15:49:22 (1 gebeurtenissen)
Laatst gelogd: 15:49:22

Error occurred loading flow for integration hon: Error loading shared library /usr/local/lib/python3.12/site-packages/_awscrt.abi3.so: Exec format error

Checked, File is present.
-------------------------------------------------------------------------------------------------------------

Logger: homeassistant.helpers.typing
Bron: helpers/deprecation.py:197
Eerst voorgekomen: 15:49:21 (2 gebeurtenissen)
Laatst gelogd: 15:49:22

HomeAssistantType was used from hon, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'hon' custom integration
HomeAssistantType was used from hon, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please create a bug report at https://github.com/Andre0512/hon/issues

--------------------------------------------------------------------------------------------------------------------------------------

Logger: homeassistant.util.loop
Bron: util/loop.py:136
Eerst voorgekomen: 15:49:22 (1 gebeurtenissen)
Laatst gelogd: 15:49:22

Detected blocking call to import_module with args ('custom_components.hon.config_flow',) inside the event loop by integration 'config' at homeassistant/components/config/config_entries.py, line 179: return await super()._post_impl(request, data) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1296: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+config%22 For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle return await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post return await self._post_impl(request, data) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl return await super()._post_impl(request, data)

**Device Log**
Post your device info here (if available)
Rpi4, running on SSD, HA in Docker, docker is up to date

**Data Archive**
For further analysis, please add your appliance data archive here (if available)
Navigate to `Settings` -> `Device & Services` -> `Haier hOn` -> _your device_ and press the _Create Data Archive_ button. 
Then open notifications to download the data zip archive.
To attach the file:
* GitHub Web: Use the "Attach files by dragging & dropping, selecting or pasting them." function
* GitHub Mobile: Upload the zip archive as image

**Comment by bvdf0251** [comment]
pip install --force-reinstall python solved the issue.

Please consider it done and close it.
