### ISSUE TITLE
RuntimeError: 'hon' calls async_write_ha_state

### ISSUE THREAD

**Issue by gio-dzilla** [Andre0512/hon#269]
**Describe the bug**

RuntimeError: Detected that custom integration 'hon' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. 

**Environment (please complete the following information):**
 - Core 2024.12.4
- Supervisor 2024.12.0
 - hOn Integration Version 0.14.0
 - pyhOn Version [e.g. `0.13.1`, can be found in device log]

**Home Assistant Logs**

RuntimeError: Detected that custom integration 'hon' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/hon/sensor.py, line 877: self.async_write_ha_state(). Please report it to the author of the 'hon' custom integration
Exception ignored in: <class 'RuntimeError'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/awscrt/mqtt5.py", line 1471, in _on_publish
    self._on_publish_cb(PublishReceivedData(publish_packet=publish_packet))
  File "/usr/local/lib/python3.13/site-packages/pyhon/connection/mqtt.py", line 105, in _on_publish_received
    self._hon.notify()
  File "/usr/local/lib/python3.13/site-packages/pyhon/hon.py", line 130, in notify
    self._notify_function(None)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 514, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
  File "/config/custom_components/hon/sensor.py", line 877, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1022, in async_write_ha_state
    report_non_thread_safe_operation("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 368, in report_non_thread_safe_operation
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 164, in report
    report_usage(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 242, in report_usage
    _report_integration_frame(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 340, in _report_integration_frame
    raise RuntimeError( from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/hon/sensor.py, line 877: self.async_write_ha_state(). Please report it to the author of the 'hon' custom integration

[dw_10067.zip](https://github.com/user-attachments/files/18195286/dw_10067.zip)

**Data Archive**
For further analysis, please add your appliance data archive here (if available)
Navigate to `Settings` -> `Device & Services` -> `Haier hOn` -> _your device_ and press the _Create Data Archive_ button. 
Then open notifications to download the data zip archive.
To attach the file:
* GitHub Web: Use the "Attach files by dragging & dropping, selecting or pasting them." function
* GitHub Mobile: Upload the zip archive as image

**Comment by galvani** [comment]
same here, and the status of appliance is not being update, only on reload

```
2024-12-26 09:47:03.917 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration hon with title: gxxxxxxxx@gmail.com and entry_id: 01JG1xxxxxxxxxxxxxxx, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue
homeassistant  | Stack (most recent call last):
homeassistant  |   File "<frozen runpy>", line 198, in _run_module_as_main
homeassistant  |   File "<frozen runpy>", line 88, in _run_code
homeassistant  |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
homeassistant  |     sys.exit(main())
homeassistant  |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
homeassistant  |     exit_code = runner.run(runtime_conf)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
homeassistant  |     return loop.run_until_complete(setup_and_run_hass(runtime_config))
homeassistant  |   File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
homeassistant  |     self.run_forever()
homeassistant  |   File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
homeassistant  |     self._run_once()
homeassistant  |   File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
homeassistant  |     handle._run()
homeassistant  |   File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
homeassistant  |     self._context.run(self._callback, *self._args)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2353, in async_forward_entry_setup
homeassistant  |     _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
homeassistant  |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1199, in _report_non_awaited_platform_forwards
homeassistant  |     report_usage(
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 234, in report_usage
homeassistant  |     _LOGGER.warning(msg, stack_info=True)
```

**Comment by gio-dzilla** [comment]
Same. I have an automation that reloads the integration every X minutes. I am not sure though how good it is for the system.

**Comment by galvani** [comment]
> Same. I have an automation that reloads the integration every X minutes. I am not sure though how good it is for the system.

Could you share the automation, I don't know how to reload whole integration and reloading just entity does not work well. e.g. **phase** which fails with:

```
2024-12-27 22:30:00.180 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.hd_495ambb_1_s_phase fails
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
homeassistant  |     await self.async_device_update()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
homeassistant  |     await self.async_update()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 596, in async_update
homeassistant  |     await self.coordinator.async_request_refresh()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 274, in async_request_refresh
homeassistant  |     await self._debounced_refresh.async_call()
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in async_call
homeassistant  |     await task
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 355, in async_refresh
homeassistant  |     await self._async_refresh(log_failures=True)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
homeassistant  |     self.data = await self._async_update_data()
homeassistant  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 279, in _async_update_data
homeassistant  |     raise NotImplementedError("Update method not implemented")
homeassistant  | NotImplementedError: Update method not implemented
```

yet another issue is:
```
homeassistant  | 2024-12-27 22:30:10.181 ERROR (MainThread) [custom_components.hon] Unexpected exception from <bound method DataUpdateCoordinator.async_refresh of <homeassistant.helpers.update_coordinator.DataUpdateCoordinator object at 0x7f6c251810>>
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 137, in _handle_timer_finish
homeassistant  |     await task
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 355, in async_refresh
homeassistant  |     await self._async_refresh(log_failures=True)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
homeassistant  |     self.data = await self._async_update_data()
homeassistant  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 279, in _async_update_data
homeassistant  |     raise NotImplementedError("Update method not implemented")
homeassistant  | NotImplementedError: Update method not implemented
```

**Comment by galvani** [comment]
@gio-dzilla I managed with help of AI to enable updating. I have created a pull request
https://github.com/Andre0512/hon/pull/274

you can overwrite the custom_components/hon with this branch: https://github.com/galvani/hon/tree/fix/fix-updating-entity

**Comment by gio-dzilla** [comment]
> @gio-dzilla I managed with help of AI to enable updating. I have created a pull request #274
> 
> you can overwrite the custom_components/hon with this branch: https://github.com/galvani/hon/tree/fix/fix-updating-entity

Amazing! You are a star! Thanks for working on this.

**Comment by KameDomotics** [comment]
> @gio-dzilla I managed with help of AI to enable updating. I have created a pull request
> 
> https://github.com/Andre0512/hon/pull/274
> 
> 
> 
> you can overwrite the custom_components/hon with this branch: https://github.com/galvani/hon/tree/fix/fix-updating-entity
> 
> 

I can't open this link, "try again error"

**Comment by galvani** [comment]
https://github.com/galvani/hon/tree/fix/fix-updating-entity

**Comment by galvani** [comment]
works just fine at my end, it's github

**Comment by gio-dzilla** [comment]
> > @gio-dzilla I managed with help of AI to enable updating. I have created a pull request
> > #274
> > you can overwrite the custom_components/hon with this branch: https://github.com/galvani/hon/tree/fix/fix-updating-entity
> 
> I can't open this link, "try again error"

Works fine for me too

**Comment by KameDomotics** [comment]
> works just fine at my end, it's github

I currently don't have any hOn integrations installed (because they all had problems). If I wanted to install one directly with your fix, which repository should I download it from?

**Comment by KameDomotics** [comment]
> works just fine at my end, it's github

Adding your repo, I can't even download the custom component

![image](https://github.com/user-attachments/assets/30a5acfa-2fee-4c62-9a73-80408ce6f06d)

**Comment by galvani** [comment]
I did not create the package, you should have just overwritten the files in your installation. now I did. event the hacs method should wiork:
![image](https://github.com/user-attachments/assets/a61565ef-4a35-4431-a581-4b00b2ab919a)

**Comment by KameDomotics** [comment]
> I did not create the package, you should have just overwritten the files in your installation. now I did. event the hacs method should wiork:
> 
> ![image](https://github.com/user-attachments/assets/a61565ef-4a35-4431-a581-4b00b2ab919a)
> 
> 

Which repo is this screenshot referring to? Yours or Andre0512's? I'm getting a bit confused

**Comment by KameDomotics** [comment]
Unfortunately it doesn't work, it's the usual problems and limitations imposed by Haier some time ago. 
I haven't used it for months due to the constant problems and unreliability, I will continue not to use it.

(failed to set up error)

**Comment by gio-dzilla** [comment]
> Unfortunately it doesn't work, it's the usual problems and limitations imposed by Haier some time ago. I haven't used it for months due to the constant problems and unreliability, I will continue not to use it.
> 
> (failed to set up error)

It’s working for me. It doesn’t resolve the other issues with the integration, but at least now the info are updated regularly and reliably I just downloaded the file that @galvani edited and upload it to the custom_component/hon folder.

**Comment by KameDomotics** [comment]
It works as poorly as ever, has never worked well and will never work well, despite the different forks and versions.
For example not all entities update, here the Stage entity updates in the Drying state, but the Machine Status entity is always in the Ready state.
This also makes it difficult to do automations.


![image](https://github.com/user-attachments/assets/d6dc014f-4749-4745-9cfd-c8b3a348a428)

**Comment by gio-dzilla** [comment]
> It works as poorly as ever, has never worked well and will never work well, despite the different forks and versions. For example not all entities update, here the Stage entity updates in the Drying state, but the Machine Status entity is always in the Ready state. This also makes it difficult to do automations.
> 
> ![image](https://private-user-images.githubusercontent.com/47695661/402289948-d6dc014f-4749-4745-9cfd-c8b3a348a428.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY2NzY4NTEsIm5iZiI6MTczNjY3NjU1MSwicGF0aCI6Ii80NzY5NTY2MS80MDIyODk5NDgtZDZkYzAxNGYtNDc0OS00NzQ1LTljZmQtYzhiM2EzNDhhNDI4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExMlQxMDA5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGNmMzc4Yzc4YTM0NTA3NTE2YzZiNTQ5ZThiOWYyNWY0ZjljMmI4ODkyNmFlNWYzNjlhNGJlNjJiN2U0MTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EK2IDRS8642ylzK-P6Fn2n0Q4pB0z9rFJHHEtPtqi-E)

A me funziona (bene).

**Comment by KameDomotics** [comment]
> > It works as poorly as ever, has never worked well and will never work well, despite the different forks and versions. For example not all entities update, here the Stage entity updates in the Drying state, but the Machine Status entity is always in the Ready state. This also makes it difficult to do automations.
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/47695661/402289948-d6dc014f-4749-4745-9cfd-c8b3a348a428.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY2NzY4NTEsIm5iZiI6MTczNjY3NjU1MSwicGF0aCI6Ii80NzY5NTY2MS80MDIyODk5NDgtZDZkYzAxNGYtNDc0OS00NzQ1LTljZmQtYzhiM2EzNDhhNDI4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExMlQxMDA5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGNmMzc4Yzc4YTM0NTA3NTE2YzZiNTQ5ZThiOWYyNWY0ZjljMmI4ODkyNmFlNWYzNjlhNGJlNjJiN2U0MTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EK2IDRS8642ylzK-P6Fn2n0Q4pB0z9rFJHHEtPtqi-E)
> 
> 
> 
> A me funziona (bene). 

A me non ha mai funzionato bene, ho sia lavatrice che asciugatrice Candy hOn, e c'è sempre qualcosa che non va.
Ad esempio il tempo residuo della lavatrice non arriva mai a zero, ma rimane sempre qualche minuto (a volte 1, a volte 4 ecc ecc)

**Comment by gio-dzilla** [comment]
> > > It works as poorly as ever, has never worked well and will never work well, despite the different forks and versions. For example not all entities update, here the Stage entity updates in the Drying state, but the Machine Status entity is always in the Ready state. This also makes it difficult to do automations.
> > 
> > 
> > > 
> > 
> > 
> > > ![image](https://private-user-images.githubusercontent.com/47695661/402289948-d6dc014f-4749-4745-9cfd-c8b3a348a428.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY2NzY4NTEsIm5iZiI6MTczNjY3NjU1MSwicGF0aCI6Ii80NzY5NTY2MS80MDIyODk5NDgtZDZkYzAxNGYtNDc0OS00NzQ1LTljZmQtYzhiM2EzNDhhNDI4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExMlQxMDA5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGNmMzc4Yzc4YTM0NTA3NTE2YzZiNTQ5ZThiOWYyNWY0ZjljMmI4ODkyNmFlNWYzNjlhNGJlNjJiN2U0MTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EK2IDRS8642ylzK-P6Fn2n0Q4pB0z9rFJHHEtPtqi-E)
> > 
> > 
> > A me funziona (bene).
> 
> A me non ha mai funzionato bene, ho sia lavatrice che asciugatrice Candy hOn, e c'è sempre qualcosa che non va. Ad esempio il tempo residuo della lavatrice non arriva mai a zero, ma rimane sempre qualche minuto (a volte 1, a volte 4 ecc ecc)

![Image](https://github.com/user-attachments/assets/d185546d-51ed-4c2a-be39-4833e5b099e8)

Fully working here.
