### ISSUE TITLE
H9A3TCBEXS-S

### ISSUE THREAD

**Issue by killone78** [Andre0512/hon#36]
With this model dryer i have the numbers in place of names for the following sensors: Machine Status (2) and Program (35 or unknown program 0) 
![dryer](https://user-images.githubusercontent.com/86172691/235379625-6c9fb1ee-6314-4cf2-805e-9c9420413167.JPG)

**Comment by Andre0512** [comment]
Hi, should be fixed now checkout the latest version :slightly_smiling_face:

**Comment by killone78** [comment]
with new version 1.7 i have this error: Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 31, in async_setup_entry
    hon = await Hon(
  File "/usr/local/lib/python3.10/site-packages/pyhon/hon.py", line 41, in create
    await self.setup()
  File "/usr/local/lib/python3.10/site-packages/pyhon/hon.py", line 67, in setup
    await self._create_appliance(appliance)
  File "/usr/local/lib/python3.10/site-packages/pyhon/hon.py", line 52, in _create_appliance
    await asyncio.gather(
  File "/usr/local/lib/python3.10/site-packages/pyhon/appliance.py", line 203, in load_commands
    await self._recover_last_command_states()
  File "/usr/local/lib/python3.10/site-packages/pyhon/appliance.py", line 149, in _recover_last_command_states
    command.category = parameters.pop("category")
KeyError: 'category'

**Comment by Andre0512** [comment]
Please test `v0.7.1`

**Comment by killone78** [comment]
With 0.7.1 it works but many sensors are missing, upgrading to the latest version 0.7.3 only Program is missing
![HON](https://github.com/Andre0512/hon/assets/86172691/3632fda1-90a9-4b61-9952-960bec9712ac)
thanks for the great work :)
