### ISSUE TITLE
User Favorites

### ISSUE THREAD

**Issue by Lu-Fi** [Andre0512/hon#47]
Hi, short question, within the Handy App you can define User Favorite programms and Names.
If i configure something on my Phone (apple), my wife can also see this on her Phone (Andoid).
Do you know if it's also possible to make this available here ? 

*EDIT*
This question is regarding Washing Programs .....

**Comment by Andre0512** [comment]
Hey, I just have a look at it and it's possible :slightly_smiling_face: 
I will add favorites as additional programs in the future :+1:

**Comment by Andre0512** [comment]
Hey, can you please test `v0.8.0-beta.8`? Favorites should be shown now :slightly_smiling_face:

**Comment by Lu-Fi** [comment]
Hi, yes they are shown. Will try functionallity next days. 
many thx..

**Comment by Lu-Fi** [comment]
I can select a Favorite, but on some of them, selection jumps over to the next one. After selecting a Programm and pressing the Washingmaschine button ,program starts, but sensors showing not the right program.
Since i selected "All in one '59" the sensor reports "Active Wash + Steam". Also the selected Opions(Vorspülen) are not reported by the sensors. 
On my Phone App it looks ok.

**Comment by Lu-Fi** [comment]
Since today i receive:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/hon/__init__.py:31
Integration: Haier hOn (documentation, issues)
First occurred: 08:40:46 (2 occurrences)
Last logged: 17:04:36

Error setting up entry xx@xx.de for hon
Error setting up entry xx@xx.de for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 31, in async_setup_entry
    hon = await Hon(
  File "/usr/local/lib/python3.10/site-packages/pyhon/hon.py", line 61, in create
    await self.setup()
  File "/usr/local/lib/python3.10/site-packages/pyhon/hon.py", line 91, in setup
    for appliance in (await self.api.load_appliances())["payload"]["appliances"]:
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/api.py", line 69, in load_appliances
    async with self._hon.get(f"{const.API_URL}/commands/v1/appliance") as resp:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/handler/base.py", line 44, in get
    async with self._intercept(self._session.get, *args, **kwargs) as response:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/handler/hon.py", line 58, in _intercept
    kwargs["headers"] = await self._check_headers(kwargs.get("headers", {}))
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/handler/hon.py", line 49, in _check_headers
    await self.auth.authenticate()
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/auth.py", line 245, in authenticate
    if not (url := await self._login()):
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/auth.py", line 182, in _login
    await self._error_logger(response)
  File "/usr/local/lib/python3.10/site-packages/pyhon/connection/auth.py", line 83, in _error_logger
    raise exceptions.HonAuthenticationError("Can't login")
pyhon.exceptions.HonAuthenticationError: Can't login


{"event":{"descriptor":"markup://aura:systemError","attributes":{"values":{"message":"[AuraClientInputException from server] Unexpected request input. Expected input format: \"Data in a request must be a valid JSON Object and must be in the expected format.\".","showOverride":false}},"eventDef":{"descriptor":"markup://aura:systemError","t":"APPLICATION","xs":"G","a":{"message":["message","aura://String","G",false],"error":["error","aura://String","G",false],"auraError":["auraError","aura://Object","I",false,null],"timestamp":["timestamp","aura://Integer","I",false],"showOverride":["showOverride","aura://Boolean","I",false,false]}}},"exceptionMessage":"[AuraClientInputException from server] Unexpected request input. Expected input format: \"Data in a request must be a valid JSON Object and must be in the expected format.\".","exceptionEvent":true}/*ERROR*/ ========================================
{'error': {'message': 'not valid jwt ISS', 'code': 'VFJWTI', 'statusCode': 400}}

**Comment by Lu-Fi** [comment]
Logon issue is fixed.

Here you can see, what happens if i select "Buntwäsche" it jumps directly to the second one "Bärchen".

https://drive.google.com/file/d/1vNXo3uqkxn1tZiJPsraf25ky2QwNoZAS/view

**Comment by Andre0512** [comment]
Hi, okay I understand and will have a look. Is "Bärchen" based on "Buntwäsche"? You can remove it if you want :+1:

**Comment by Andre0512** [comment]
> but sensors showing not the right program.
The program name thing is a bit tricky, I will have a look at it.

> I'am missing some settings here, this mashine has an option to select a dirt level (0,1,2) and provides an option named "Hygiene".

Can you show your device log? Maybe we could add these settings.

> What happens, if you select an Favorite and this options are not implemented ? 
It should be use the programs default value and for favorites it should use the configured value :slightly_smiling_face:

**Comment by Lu-Fi** [comment]
> Hi, okay I understand and will have a look. Is "Bärchen" based on "Buntwäsche"? You can remove it if you want

Don't know if "Bärchen" is based in "Buntwäsche" but both are based on the same original program.



> Can you show your device log? Maybe we could add these settings.

Something like this ? https://github.com/Andre0512/hon/issues/42#issuecomment-1546900135

**Comment by Lu-Fi** [comment]
How do you get the Favorit settings ? in pyhOn.py i only see the names, but no info about the program details.
