### ISSUE TITLE
Integration can't start.

### ISSUE THREAD

**Issue by finalbillybong** [Andre0512/hon#60]
Here are the logs.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/haier_hon/__init__.py", line 31, in async_setup_entry
    hon = await Hon(
  File "/usr/local/lib/python3.10/site-packages/pyhon/hon.py", line 61, in create
    await self.setup()
  File "/usr/local/lib/python3.10/site-packages/pyhon/hon.py", line 95, in setup
    await self._create_appliance(appliance)
  File "/usr/local/lib/python3.10/site-packages/pyhon/hon.py", line 77, in _create_appliance
    await asyncio.gather(
  File "/usr/local/lib/python3.10/site-packages/pyhon/appliance.py", line 218, in load_commands
    await self._add_favourites()
  File "/usr/local/lib/python3.10/site-packages/pyhon/appliance.py", line 235, in _add_favourites
    parameter.value = value
  File "/usr/local/lib/python3.10/site-packages/pyhon/parameter/range.py", line 58, in value
    if self._min <= value <= self._max and not (value - self._min) % self._step:
ZeroDivisionError: float modulo
```

**Comment by Zaleo80** [comment]
+1

**Comment by Zaleo80** [comment]
Guess it is related to the python 3.10 to 3.11 update ?

**Comment by finalbillybong** [comment]
I’m still on 2923.5.x so I don’t think so.

**Comment by Andre0512** [comment]
Hi, please checkout the latest beta version, should be fixed now

**Comment by finalbillybong** [comment]
I installed beta 10 and now get a different error.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier_hon/__init__.py", line 31, in async_setup_entry
    hon = await Hon(
          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhon/hon.py", line 61, in create
    await self.setup()
  File "/usr/local/lib/python3.11/site-packages/pyhon/hon.py", line 95, in setup
    await self._create_appliance(appliance)
  File "/usr/local/lib/python3.11/site-packages/pyhon/hon.py", line 77, in _create_appliance
    await asyncio.gather(
  File "/usr/local/lib/python3.11/site-packages/pyhon/appliance.py", line 218, in load_commands
    await self._add_favourites()
  File "/usr/local/lib/python3.11/site-packages/pyhon/appliance.py", line 235, in _add_favourites
    parameter.value = value
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhon/parameter/range.py", line 58, in value
    if self._min <= value <= self._max and not (value - self._min) % self._step:
                                               ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
ZeroDivisionError: float modulo
```

**Comment by Andre0512** [comment]
Did you restart? In pyhOn `v0.12.2` this line should look a bit different :thinking:

**Comment by Zaleo80** [comment]
Downloaded [v0.8.0-beta.10](https://github.com/Andre0512/hon/releases/tag/v0.8.0-beta.10) and put it in the config\custom_components\hon folder overwriting all duplicated files.

Reloaded HA, also I can confirm the issue is resolved. Highly appriciated.
