### ISSUE TITLE
Dry Level & Drying Time selection renders Unknown

### ISSUE THREAD

**Issue by quartstudio** [Andre0512/hon#70]
**Describe the bug**
When changing Dry Level option there is an error and state does not change:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 106, in async_select_option
    await entity.async_select_option(option)
  File "/config/custom_components/hon/select.py", line 214, in async_select_option
    self._device.settings[self.entity_description.key].value = option
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhon/parameter/range.py", line 57, in value
    value = str_to_float(value)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhon/parameter/range.py", line 10, in str_to_float
    return float(str(string).replace(",", "."))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'no_dry'

**To Reproduce**
Select dropdown option from select.washer_dryer_drying_level 

**Expected behavior**
Should change

**Environment (please complete the following information):**
 - Home Assistant Version:2023.6.1
 - hOn Integration Version 0.9.-beta 9
 - pyhOn Version: 0.13.0

Also, the "Drying Time" state does not update/reflect in HA. Instead renders Unknown.
Thank you.

**Comment by Andre0512** [comment]
Hi, thanks for reporting! I released a new beta, check it out :slightly_smiling_face:

**Comment by quartstudio** [comment]
Works! Thank you!
