### ISSUE TITLE
NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tempus2016** [Andre0512/hon#77]
Started getting this since the last update. 

```
This error originated from a custom integration.

Logger: custom_components.hon.hon
Source: custom_components/hon/hon.py:64 
Integration: Haier hOn (documentation, issues) 
First occurred: 18 June 2023 at 23:09:49 (1 occurrences) 
Last logged: 18 June 2023 at 23:09:49

Unexpected error fetching a8-48-fa-18-ef-e4 data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/hon.py", line 64, in _async_update_data
    await self._device.update()
  File "/usr/local/lib/python3.11/site-packages/pyhon/appliance.py", line 261, in update
    await self.load_attributes()
  File "/usr/local/lib/python3.11/site-packages/pyhon/appliance.py", line 246, in load_attributes
    self._attributes = self._extra.attributes(self._attributes)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyhon/appliances/td.py", line 8, in attributes
    if data["lastConnEvent"]["category"] == "DISCONNECTED":
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

```

**Comment by Andre0512** [comment]
Hi, which version do you use?

**Comment by tempus2016** [comment]
V9-beta3. Latest HAOS and Supervisor.

**Comment by Andre0512** [comment]
Thanks, please checkout the latest beta version.
